server:
  port: 6200
  ssl:
    key-store: sslkeystore.p12
    enabled: true
    key-store-type: PKCS12
    key-store-password: mypass
    key-alias: tomcat
  tomcat:
    max-threads: 400
    accept-count: 400
spring:
  application:
    name: eureka-load-balancer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
#    secure-port: ${server.port}
#    secure-port-enabled: true

services:
  db_one: db-api-spring
  db_two: db-api-fraud-guard